aws_region                      = "us-west-2"
rds_subnet_ids                  = ["subnet-0aafb2646b47c986e", "subnet-09d8824b9c18a9382"]
vpc_id                          = "vpc-06bc40fbf7fd648cd"
db_engine_version               = "15"
db_instance_class               = "db.t3.micro"
allocated_storage               = 20
storage_type                    = "gp3"
multi_az                        = false
kms_key_id                      = "" # or "arn:aws:kms:..."
master_username                 = "masteruser"
master_user_password            = "SuperSecretPwd123!"
db_name                         = "dbtest"
db_engine = "postgres"
backup_retention_days           = 7
preferred_backup_window         = ""
preferred_maintenance_window    = ""
deletion_protection             = true
allowed_cidr_for_db_port        = "" # e.g. "1.2.3.4/32"
allowed_security_group_id       = "" # e.g. "sg-aaa111"
enable_performance_insights     = true
enabled_cloudwatch_logs_exports = []
